server {

    listen 80;

    server_name localhost;

    root /var/www/project02;

    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    access_log /var/log/nginx/project02_access.log;

    error_log /var/log/nginx/project02_error.log;

}
